### ISSUE TITLE
Kaku pauses media when the service is started

### ISSUE THREAD

**Issue by 0xbad1d3a5** [0xbad1d3a5/Kaku#11]

**Comment by 0xbad1d3a5** [comment]
This was caused by the tutorial videos. Since the tutorial videos are no longer part of MainActivity, this shouldn't happen anymore, except when users launch the tutorial. IMO this is good enough.

If there is a need to fix this in the future though: https://stackoverflow.com/questions/48503017/videoview-is-stopping-music-player

**Comment by weirdalsuperfan** [comment]
It wasn't fixed last night, but I guess I didn't check again after updating. It seems to be fixed now. Hurray!
