### ISSUE TITLE
not detecting words 

### ISSUE THREAD

**Issue by max1236** [0xbad1d3a5/Kaku#14]
I looked up the word 搾取する and it came up exactly like that in the ocr but it only detects the first kanji. also I dont see a way to copy the whole text to clipboard.

**Comment by 0xbad1d3a5** [comment]
Can you elaborate a bit more? I'm able to get the lookup for 搾取 just fine, in both instant mode and normal mode:

![screenshot_20190217-211134](https://user-images.githubusercontent.com/878158/52929454-58d35080-32f9-11e9-9b9b-cdd48d82dfd6.png)
![screenshot_20190217-211150](https://user-images.githubusercontent.com/878158/52929455-58d35080-32f9-11e9-904c-64317644931d.png)

Can you try joining the beta in the Play Store and see if it's still an issue in the beta version? The beta version has quite a few bugfixes that the public version does not.

You can also copy the visible part of the text to the clipboard by holding down on any of the kanjis in the dictionary window / instant window.

**Comment by max1236** [comment]
hmm I tried it a gain today and it works.
