### ISSUE TITLE
Auto share on copy text

### ISSUE THREAD

**Issue by SpongebobSquamirez** [0xbad1d3a5/Kaku#26]
Requesting the ability to have an option in the settings for automatically sharing text when it's copied.

Right now part of my workflow consists of copying the text and then shaking my phone to open a fast sharing app (Fliktu) that replaces the default and opens almost immediately, but it's not only an extra step, it's also finicky. I figure people copy things for sharing (whether to have it get sent to Google translate or some other app), so I imagine a lot of people would value this. For me it would just cut out the work and uncertainty with sharing. For some reason if Fliktu doesn't work the first time on some copied text, I have to copy some other text (not the same text) before it'll start working again, almost as if it doesn't want to annoy users by working on the same text...even if you copy it again...which makes it unreliable on top of time consuming. This isn't a bug with Kaku, but anyway it'd be a really handy time-saving feature that makes a lot of sense and probably could be implemented in 20 minutes.

**Comment by 0xbad1d3a5** [comment]
I don't think I'm going to take this currently or as is.

The current gesture system / UI will likely need a slight overhaul anyways once I start working on anki/similar support (maybe after the Sakura milestone?) so I'd rather not work on one-off's that'll need to be rewritten anyways.

**Comment by 0xbad1d3a5** [comment]
Just so I know for more context though, what's the workflow here with Fliktu? Just Anki integration or something else?

**Comment by SpongebobSquamirez** [comment]
It's just Anki integration right now, although if I could copy individual words that'd be handy for looking up in my J-J dictionaries via Fliktu as well. The benefit of Fliktu is it's basically instant and configurable. The normal sharing function takes 5-10 seconds to load.

This is what I do:

I find a word I want, I put the OCR box over it -> screenshot, crop the image, save -> double-tap the OCR window, correct errors, look at the English translation of the word if it's found (e.g. all kana conjugations won't be) -> long tap to copy -> quickly shake/flick my phone, which activates Fliktu if I do it properly (it only activates like that after copying something) -> select Anki from the share list (which directly goes into the make card interface) -> paste the OCR'd text into the sentence field, paste it into the expression field and cut off everything besides the word -> add an image to the image field, select the most recent picture from my phone's gallery (the one I just screenshotted/cropped -> save the card -> later on my pc I sync, run my addons to generates definitions/readings/pronunciation/audio, and I'm good to go
