### ISSUE TITLE
F-Droid distribution

### ISSUE THREAD

**Issue by deliciouslytyped** [0xbad1d3a5/Kaku#31]
Have you considered distributing Kaku on https://f-droid.org/ ?

I saw the dialog about valuing users privacy & etc., if you aren't familiar with F-Droid - I'm not an android developer but - it seem's to take users freedoms seriously. There is the #fdroid-dev channel on freenode if you use IRC, for help if necessary.

**Comment by SpongebobSquamirez** [comment]
See #28
