### ISSUE TITLE
[Feature request] Chinese support 

### ISSUE THREAD

**Issue by kevinchua6** [0xbad1d3a5/Kaku#41]
I've been trying to find something like kaku for Chinese but to no avail. 

Would it be difficult to release a separate app for Chinese? I would be glad to contribute to something like that. 

Thanks!

**Comment by 0xbad1d3a5** [comment]
It's not too difficult, but I don't think I have the time to help out - feel free to fork the code!

You'd honestly get yourself 90% there if you just replace the sqlite database with a Chinese version (it has a pretty simple schema) and swap out the tesseract files from JPN > CN.

There is actually an app that does something similar to Kaku on the Play Store for Chinese (it's paid though, and not sure if it's been updated - Android's restrictions on SYSTEM_ALERT_WINDOW being 70% opacity may prevent it from running on newer devices), so if you're too lazy, maybe give this a try: https://www.youtube.com/watch?v=5f5YRc_yRtA

**Comment by kevinchua6** [comment]
Thanks for the guidance! I'll try my hand at forking this and seeing how it goes. I probably won't risk buying the app because it seems quite old. Thanks again!
